version: '3'
services:
  falko-test:
    container_name: falko-test
    build: 
      context: .
      dockerfile: Dockerfile.test
    command: bash -c "./wait-4-postgres.sh && sleep infinity"
    environment:
      - RAILS_ENV=test
    ports:
      - 3000
    depends_on:
      - falko-database

  falko-database:
    container_name: falko-database
    image: postgres:9.6
    ports: 
      - 5432
    environment:
      - PG_USER=postgres
      - PG_DATABASE=travis_ci_test
    volumes:
      - ./tmp/data/postgresql:/postgresql
      - .:/Falko-2017.2-BackEnd
