default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: Falko-2017_2-BackEnd_development

test:
  <<: *default
  database: travis_ci_test

production:
  adapter: postgresql
  database: Falko-2017_2-BackEnd_production
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  url: <%= ENV["DATABASE_URL"] %>
  host: dokku.postgres.falko-database
  
