default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 
  host: falko-database


development: &development
  <<: *default
  database: Falko-2017_2-BackEnd_development

test:
  <<: *default
  adapter: postgresql
  database: travis_ci_test

production:
  <<: *default
  adapter: postgresql
  database: Falko-2017_2-BackEnd_production
  
